"""Local STAC catalog of generated composite COGs.

Every composite the pipeline produces is registered as a STAC Item in a
self-contained catalog under ``data/<region>/composites/``, so downstream
stages (and external tools) discover imagery through STAC rather than path
conventions.
"""

from __future__ import annotations

import os
from datetime import UTC, datetime
from pathlib import Path

import pystac
import pystac.stac_io
import rasterio
import rasterio.warp
from loguru import logger
from shapely.geometry import box, mapping


class _AtomicStacIO(pystac.stac_io.DefaultStacIO):
    """Write catalog JSON via tmp-file + rename so a crash mid-write can never
    leave a half-written (binary-garbage) catalog behind."""

    def write_text_to_href(self, href: str, txt: str) -> None:
        dest = Path(href)
        dest.parent.mkdir(parents=True, exist_ok=True)
        tmp = dest.with_suffix(dest.suffix + ".tmp")
        tmp.write_text(txt, encoding="utf-8")
        os.replace(tmp, dest)


def _open_or_create(catalog_path: Path, region: str) -> pystac.Catalog:
    if catalog_path.exists():
        try:
            return pystac.Catalog.from_file(str(catalog_path))
        except (ValueError, pystac.STACError) as exc:
            # e.g. power loss mid-write left garbage bytes. Safe to rebuild:
            # the COGs are the source of truth and the composite stage
            # re-registers every fresh tile on each run.
            logger.warning(
                "Local STAC catalog {} is corrupt ({}) — rebuilding from scratch",
                catalog_path,
                type(exc).__name__,
            )
    catalog = pystac.Catalog(
        id=f"rooftopsenti-{region}",
        description=f"Cloud-free Sentinel-2 composites for region '{region}' "
        "generated by rooftopsenti",
    )
    catalog.normalize_hrefs(str(catalog_path.parent))
    return catalog


def register_composite(
    catalog_path: Path,
    region: str,
    tile: str,
    range_idx: int,
    cog_path: Path,
    date_range: tuple[str, str],
    bands: list[str],
) -> pystac.Item:
    """Add (or replace) a STAC item for one composite COG and save the catalog.

    Guarded by a file lock so parallel composite workers can register items
    without racing on the catalog's read-modify-write.
    """
    import fcntl

    catalog_path.parent.mkdir(parents=True, exist_ok=True)
    lock_path = catalog_path.with_suffix(".lock")
    with open(lock_path, "w") as lock_file:
        fcntl.flock(lock_file, fcntl.LOCK_EX)
        try:
            return _register_composite_locked(
                catalog_path, region, tile, range_idx, cog_path, date_range, bands
            )
        finally:
            fcntl.flock(lock_file, fcntl.LOCK_UN)


def _register_composite_locked(
    catalog_path: Path,
    region: str,
    tile: str,
    range_idx: int,
    cog_path: Path,
    date_range: tuple[str, str],
    bands: list[str],
) -> pystac.Item:
    catalog = _open_or_create(catalog_path, region)

    with rasterio.open(cog_path) as src:
        bounds_native = src.bounds
        epsg = src.crs.to_epsg()
        transform = list(src.transform)[:6]
        shape = [src.height, src.width]
        bounds_wgs84 = rasterio.warp.transform_bounds(src.crs, "EPSG:4326", *bounds_native)

    start = datetime.fromisoformat(date_range[0]).replace(tzinfo=UTC)
    end = datetime.fromisoformat(date_range[1]).replace(tzinfo=UTC)
    item_id = f"{tile}_range{range_idx}"

    item = pystac.Item(
        id=item_id,
        geometry=mapping(box(*bounds_wgs84)),
        bbox=list(bounds_wgs84),
        datetime=None,
        start_datetime=start,
        end_datetime=end,
        properties={
            "mgrs:tile": tile,
            "rooftopsenti:range_idx": range_idx,
            "rooftopsenti:bands": bands,
            "proj:code": f"EPSG:{epsg}",
            "proj:shape": shape,
            "proj:transform": transform,
        },
    )
    item.add_asset(
        "composite",
        pystac.Asset(
            href=str(cog_path.resolve()),
            media_type=pystac.MediaType.COG,
            roles=["data"],
            title=f"Sentinel-2 {date_range[0]}..{date_range[1]} cloud-free composite",
        ),
    )

    existing = catalog.get_item(item_id)
    if existing is not None:
        catalog.remove_item(item_id)
    catalog.add_item(item)
    catalog.normalize_hrefs(str(catalog_path.parent))
    catalog.save(catalog_type=pystac.CatalogType.SELF_CONTAINED, stac_io=_AtomicStacIO())
    return item


def list_composites(catalog_path: Path) -> list[pystac.Item]:
    if not catalog_path.exists():
        return []
    catalog = pystac.Catalog.from_file(str(catalog_path))
    return list(catalog.get_items(recursive=True))


def composite_assets(catalog_path: Path) -> dict[tuple[str, int], Path]:
    """Map (mgrs_tile, range_idx) -> COG path from the local STAC catalog."""
    out = {}
    for item in list_composites(catalog_path):
        key = (item.properties["mgrs:tile"], item.properties["rooftopsenti:range_idx"])
        out[key] = Path(item.assets["composite"].href)
    return out
