"""Local STAC catalog of generated composite COGs.

Every composite the pipeline produces is registered as a STAC Item in a
self-contained catalog under ``data/<region>/composites/``, so downstream
stages (and external tools) discover imagery through STAC rather than path
conventions.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path

import pystac
import rasterio
import rasterio.warp
from shapely.geometry import box, mapping


def _open_or_create(catalog_path: Path, region: str) -> pystac.Catalog:
    if catalog_path.exists():
        return pystac.Catalog.from_file(str(catalog_path))
    catalog = pystac.Catalog(
        id=f"rooftopsenti-{region}",
        description=f"Cloud-free Sentinel-2 composites for region '{region}' "
        "generated by rooftopsenti",
    )
    catalog.normalize_hrefs(str(catalog_path.parent))
    return catalog


def register_composite(
    catalog_path: Path,
    region: str,
    tile: str,
    range_idx: int,
    cog_path: Path,
    date_range: tuple[str, str],
    bands: list[str],
) -> pystac.Item:
    """Add (or replace) a STAC item for one composite COG and save the catalog."""
    catalog = _open_or_create(catalog_path, region)

    with rasterio.open(cog_path) as src:
        bounds_native = src.bounds
        epsg = src.crs.to_epsg()
        transform = list(src.transform)[:6]
        shape = [src.height, src.width]
        bounds_wgs84 = rasterio.warp.transform_bounds(src.crs, "EPSG:4326", *bounds_native)

    start = datetime.fromisoformat(date_range[0]).replace(tzinfo=UTC)
    end = datetime.fromisoformat(date_range[1]).replace(tzinfo=UTC)
    item_id = f"{tile}_range{range_idx}"

    item = pystac.Item(
        id=item_id,
        geometry=mapping(box(*bounds_wgs84)),
        bbox=list(bounds_wgs84),
        datetime=None,
        start_datetime=start,
        end_datetime=end,
        properties={
            "mgrs:tile": tile,
            "rooftopsenti:range_idx": range_idx,
            "rooftopsenti:bands": bands,
            "proj:code": f"EPSG:{epsg}",
            "proj:shape": shape,
            "proj:transform": transform,
        },
    )
    item.add_asset(
        "composite",
        pystac.Asset(
            href=str(cog_path.resolve()),
            media_type=pystac.MediaType.COG,
            roles=["data"],
            title=f"Sentinel-2 {date_range[0]}..{date_range[1]} cloud-free composite",
        ),
    )

    existing = catalog.get_item(item_id)
    if existing is not None:
        catalog.remove_item(item_id)
    catalog.add_item(item)
    catalog.normalize_hrefs(str(catalog_path.parent))
    catalog.save(catalog_type=pystac.CatalogType.SELF_CONTAINED)
    return item


def list_composites(catalog_path: Path) -> list[pystac.Item]:
    if not catalog_path.exists():
        return []
    catalog = pystac.Catalog.from_file(str(catalog_path))
    return list(catalog.get_items(recursive=True))


def composite_assets(catalog_path: Path) -> dict[tuple[str, int], Path]:
    """Map (mgrs_tile, range_idx) -> COG path from the local STAC catalog."""
    out = {}
    for item in list_composites(catalog_path):
        key = (item.properties["mgrs:tile"], item.properties["rooftopsenti:range_idx"])
        out[key] = Path(item.assets["composite"].href)
    return out
